# Generated by Django 5.1.3 on 2024-11-17 04:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Название тикета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание тикета')),
                ('priority', models.CharField(blank=True, choices=[('Приоритет 1', 'Приоритет 1'), ('Приоритет 2', 'Приоритет 2'), ('Приоритет 3', 'Приоритет 3')], default='Обычный', max_length=50, verbose_name='Приоритет')),
                ('status', models.CharField(blank=True, choices=[('Ожидает', 'Ожидает'), ('В процессе', 'В процессе'), ('Фидбэк', 'Фидбэк'), ('Закрыт', 'Закрыт')], default='Ожидает', max_length=50, verbose_name='Статус')),
                ('date_create', models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 17, 7, 36, 56, 48839), null=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
        ),
    ]
